# Generated by Django 5.1.4 on 2024-12-20 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_number', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_type', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('is_received', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
